### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by codemis** [bolt/Members#38]
I am trying to install the latest version of this plugin on Bolt 2.2.23, and am unable to do it.  Here is the information composer is sending back:

```
Composer Error

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bolt/members v2.1.2 -> satisfiable by bolt/members[v2.1.2].
    - bolt/members v2.1.2 requires bolt/clientlogin >=2.0.0,<2.2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see this link for more details.

Read this link for further common problems.
```
Can you help me with this?

**Comment by GawainLynch** [comment]
The library that ClientLogin ran under was so badly broken. So it had to go bye-bye :smile: 

Short version, there is no version that will run on Bolt 2. The `dev-master` version of Members we use a bit now, and it is running the extensions marketplace site's author identity management and login. But requires Bolt 3 due to some rather major internal improvements.

**Comment by codemis** [comment]
Thank you very much.  Since I am starting to develop the website,  I will use Bolt 3 and your dev-master.  Thank you for your help and fast reply. :-)

**Comment by GawainLynch** [comment]
Just a heads up, docs are light, I just haven't had the time :disappointed:

**Comment by codemis** [comment]
No problem.  I totally know the feeling.
