### ISSUE TITLE
[RFE] members admin area could be more intuitive

### ISSUE THREAD

**Issue by leggewie** [bolt/Members#70]
Thank you VERY much for providing the members extension.

Right after installation the members extension admin panel is not fully functional.
- Adding a user via the admin panel works
- it's entirely unclear what the buttons below are for, they are only labeled "Enable" and "Disable".  Clicking these buttons does not seem to do anything.
- Adding or deleting a role apparently does nothing

![screenshot from 2017-01-26 13 37 25](https://cloud.githubusercontent.com/assets/2387015/22321113/ed965f10-e3cc-11e6-940e-4e7acae94261.png)

**Comment by GawainLynch** [comment]
Working for us in 6 production sites, I think you have a local problem, probably the sub-directory but based on your other bug reports at the moment.

**Comment by GawainLynch** [comment]
Derp, I think I misunderstood you originally. You need to click the checkbox next to one or more user accounts to enable/disable … and for roles, you need to select something from the drop down as well.

**Comment by leggewie** [comment]
I see. If that's the intention I would suggest to use a toggle on the same line as the user to enable/disable that shows the current state at the same time to make it easier to understand the UI (and drop the enable/disable buttons for the user.

That being said, this doesn't work for me even when I first select a user and then try to apply any of the "delete user", "enable", "disable", "add role" and "remove role" buttons.

**Comment by GawainLynch** [comment]
> I would suggest to use a toggle on the same line as the user to enable/disable that shows the current state at the same time to make it easier to understand the UI (and drop the enable/disable buttons for the user in the side panel).

I am anything but a UI person. So if someone wants to have a go, PRs are welcome :smile: 

> That being said, this doesn't work for me even when I first select a user and then try to apply any of the "delete user", "enable", "disable", "add role" and "remove role" buttons.

That sounds like the JavaScript is failing to load, I would guess linked to your subdirectory problem with Bolt itself.

**Comment by leggewie** [comment]
Thanks.  I have reported the subdirectory problem as #71

**Comment by leggewie** [comment]
I can confirm that setting up a separate VHost in apache so as to serve bolt straight from the webroot instead of a subdirectory makes it possible to select and then enable or disable a member.  Thank you for the explanation.
About the PR for the UI; Well, I'm not sure I'm that much more qualified, but I'll try to provide something after getting Members at least minimally working and familiarizing myself a bit with the code.

**Comment by leggewie** [comment]
Now that things are more clearly understood and that #71 has been carved out as a separate issue, I believe the remaining task of cleaning up the UI is merely an RFE.  I will update the title accordingly.

**Comment by leggewie** [comment]
The way I would like to change the UI is to
- add members from a button either below or on top of the member list
- delete members from a knob on the member's line in the list
- enable/disable from a toggle in the member's line in the list
- add and remove roles via a drop-down in the member's line in the list
- dispense with the admin options sidebar

Is it necessary to support more than 1 role per member?  That will make the code as well as the UI more complicated.

**Comment by leggewie** [comment]
There still needs to be a way to do bulk actions as well, though.

**Comment by GawainLynch** [comment]
> Is it necessary to support more than 1 role per member? That will make the code as well as the UI more complicated.

Yes, one site we have 3 or 4 for some users.

**Comment by GawainLynch** [comment]
@bobdenotter @jadwigo @SahAssar do any of you have some feedback on this approach?

**Comment by jadwigo** [comment]
Something along the lines of the rest of the bolt back-end.

![dsc_4977-1024x1024](https://cloud.githubusercontent.com/assets/1488214/22430274/02df354c-e70e-11e6-850d-8943b7b80647.JPG)

The 'photo' can just be a generic icon, unless a gravatar or a profile meta with a real picture is present.

The edit dropdown might also harbour extra options like a link to the public profile page or remove a role

In the right bar you can add some buttons like show only disabled users, show 20 newest users, show users that have never logged in, are unverified etc..

If you want to manage multiple roles for a user you just edit the user

If you want to bulk edit roles for users you're out of luck because you cannot - and in my option that is hardly ever used anyway

**Comment by SahAssar** [comment]
IMO the best thing would be to keep it as close as is feasible to the bolt record listing (screenshot below for clarification). Specifically the enable/disable/delete should IMO be in the exact same places as the publish/depublish/delete for a record list. That'd be more familiar to all the users.

![image](https://cloud.githubusercontent.com/assets/5096632/22441471/cea56ba0-e737-11e6-9d49-b17af64d4e02.png)

**Comment by SahAssar** [comment]
Ah, this tab hadn't been reloaded for a long while, so I didn't see that @jadwigo already responded along these lines 😄

**Comment by SahAssar** [comment]
As far as the editing multiple roles that can be a dropdown next to the enable/disable/delete buttons, right?

**Comment by jadwigo** [comment]
My remark about bulk editing is specifically because we're talking UX here. I'm not yet talking about the technical feasibility, just my first response.

In my experience the bulk editing of users is something that does not happen very much because usually most users will get a default role, because that's obvious .. and some users will get some special roles.

As soon as you're talking about regularly managing large groups of users the interface with the pager is insufficient anyway. The workflow would be something along the line of select 42 users with the characteristics that you need on the first page of the memberlisting, add a role to 42 of 200 users on page one, go to page two and repeat it for 67 of 200 users, lose track of where you were and have to start over on page 3 .. etc .. 

You would need a different interface where you can for example filter on some criteria among all users and then apply a batch operation to that selection if you want to have an efficient workflow.

I really can not think of any real world scenarios where the amount of users would warrant scaling the UX up that much. A forum of thousands of users still only needs a few handful of moderators.. and you'll probably never change the status of more than 5 of them at a time. And if you have a website where you regularly have to change the role of hundreds of users by hand I think you should reconsider and build some scripts for that.

If you need to disable spam accounts in bulk, that is a different story.. you can in that interface sketch disable and/or delete users in bulk just the same way you can do that with regular content entries.

That's why I think managing multiple roles only on a per user basis is very workable for the basic extension, because then you're talking about a few handful of users that have those special roles.

Then again, there's still enough room in the right column to add the buttons and the dropdown for bulk adding and removing roles ;-)

**Comment by SahAssar** [comment]
While I think this is an awesome goal, I don't think there is currently the resources to do this. If there is I'm looking forward to the PR, but otherwise let's archive this as a "want" rather than a "need" util we can get it done.
